import { Theme } from '../types';

export const THEMES: Record<string, Theme> = {
  'modern-slate': {
    id: 'modern-slate',
    name: 'Modern Slate',
    description: 'Clean crisp canvas with slate and electric indigo accents',
    bgClass: 'bg-slate-900 text-slate-100',
    canvasBg: 'bg-slate-950',
    cardBgClass: 'bg-slate-800/80 border border-slate-700/60 shadow-xl backdrop-blur-md',
    textClass: 'text-slate-100',
    titleClass: 'text-white tracking-tight font-extrabold',
    textMutedClass: 'text-slate-400',
    accentClass: 'text-indigo-400',
    accentBgClass: 'bg-indigo-600 text-white',
    accentGlow: 'shadow-[0_0_25px_rgba(99,102,241,0.3)]',
    borderClass: 'border-slate-800',
    fontHeader: 'font-sans',
    fontBody: 'font-sans',
    dark: true,
    slideBgHex: '#0f172a',
    textColorHex: '#f8fafc',
    accentHex: '#6366f1',
  },

  'midnight-glow': {
    id: 'midnight-glow',
    name: 'Midnight Glow',
    description: 'Deep obsidian background with luminous emerald and cyan accents',
    bgClass: 'bg-zinc-950 text-zinc-100',
    canvasBg: 'bg-black',
    cardBgClass: 'bg-zinc-900/90 border border-emerald-500/30 shadow-2xl shadow-emerald-950/40',
    textClass: 'text-zinc-100',
    titleClass: 'text-white font-black tracking-tight bg-gradient-to-r from-emerald-400 via-teal-300 to-cyan-400 bg-clip-text text-transparent',
    textMutedClass: 'text-zinc-400',
    accentClass: 'text-emerald-400',
    accentBgClass: 'bg-emerald-500 text-zinc-950 font-bold',
    accentGlow: 'shadow-[0_0_30px_rgba(16,185,129,0.4)]',
    borderClass: 'border-zinc-800',
    fontHeader: 'font-sans',
    fontBody: 'font-sans',
    dark: true,
    slideBgHex: '#09090b',
    textColorHex: '#f4f4f5',
    accentHex: '#10b981',
  },

  'warm-editorial': {
    id: 'warm-editorial',
    name: 'Warm Editorial',
    description: 'Elegant cream backdrop with warm terracotta and serif typography',
    bgClass: 'bg-[#FAF8F5] text-[#292524]',
    canvasBg: 'bg-[#F2ECE4]',
    cardBgClass: 'bg-white/90 border border-[#E7E0D6] shadow-lg shadow-stone-200/50',
    textClass: 'text-[#292524]',
    titleClass: 'text-[#1C1917] font-serif font-bold tracking-normal',
    textMutedClass: 'text-[#78716C]',
    accentClass: 'text-[#C2410C]',
    accentBgClass: 'bg-[#C2410C] text-white',
    accentGlow: 'shadow-[0_4px_20px_rgba(194,65,12,0.15)]',
    borderClass: 'border-[#E7E0D6]',
    fontHeader: 'font-serif',
    fontBody: 'font-sans',
    dark: false,
    slideBgHex: '#FAF8F5',
    textColorHex: '#292524',
    accentHex: '#C2410C',
  },

  'cyber-dark': {
    id: 'cyber-dark',
    name: 'Cyber Dark',
    description: 'High-contrast dark theme with sharp neon green and tech grid vibe',
    bgClass: 'bg-black text-lime-400',
    canvasBg: 'bg-zinc-950',
    cardBgClass: 'bg-zinc-900/95 border border-lime-500/40 shadow-lg shadow-lime-950/50',
    textClass: 'text-zinc-200',
    titleClass: 'text-lime-400 font-mono tracking-wider uppercase',
    textMutedClass: 'text-zinc-400',
    accentClass: 'text-lime-400',
    accentBgClass: 'bg-lime-400 text-black font-bold',
    accentGlow: 'shadow-[0_0_20px_rgba(163,230,53,0.5)]',
    borderClass: 'border-lime-900/50',
    fontHeader: 'font-mono',
    fontBody: 'font-mono',
    dark: true,
    slideBgHex: '#000000',
    textColorHex: '#e4e4e7',
    accentHex: '#a3e635',
  },

  'nordic-minimal': {
    id: 'nordic-minimal',
    name: 'Nordic Minimal',
    description: 'Soft pastel background with ultra-clean aesthetic and subtle depth',
    bgClass: 'bg-[#F1F5F9] text-slate-800',
    canvasBg: 'bg-[#E2E8F0]',
    cardBgClass: 'bg-white border border-slate-200/80 shadow-md shadow-slate-200/60',
    textClass: 'text-slate-800',
    titleClass: 'text-slate-900 font-bold tracking-tight',
    textMutedClass: 'text-slate-500',
    accentClass: 'text-sky-600',
    accentBgClass: 'bg-sky-600 text-white',
    accentGlow: 'shadow-[0_4px_15px_rgba(2,132,199,0.2)]',
    borderClass: 'border-slate-200',
    fontHeader: 'font-sans',
    fontBody: 'font-sans',
    dark: false,
    slideBgHex: '#F1F5F9',
    textColorHex: '#1e293b',
    accentHex: '#0284c7',
  },

  'gradient-pulse': {
    id: 'gradient-pulse',
    name: 'Gradient Pulse',
    description: 'Vibrant dark violet to magenta gradient with high impact typography',
    bgClass: 'bg-gradient-to-br from-slate-950 via-purple-950 to-slate-900 text-purple-100',
    canvasBg: 'bg-black',
    cardBgClass: 'bg-purple-950/60 border border-fuchsia-500/30 backdrop-blur-lg shadow-2xl shadow-purple-950/50',
    textClass: 'text-purple-100',
    titleClass: 'text-white font-extrabold bg-gradient-to-r from-fuchsia-400 via-pink-400 to-purple-300 bg-clip-text text-transparent',
    textMutedClass: 'text-purple-300/70',
    accentClass: 'text-fuchsia-400',
    accentBgClass: 'bg-fuchsia-600 text-white font-bold',
    accentGlow: 'shadow-[0_0_30px_rgba(192,38,211,0.4)]',
    borderClass: 'border-purple-900',
    fontHeader: 'font-sans',
    fontBody: 'font-sans',
    dark: true,
    slideBgHex: '#1e1b4b',
    textColorHex: '#f3e8ff',
    accentHex: '#c026d3',
  },
};

export function getTheme(themeId: string): Theme {
  return THEMES[themeId] || THEMES['modern-slate'];
}
